[2025-04-23T05:21:20.879+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T05:21:20.882+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_delta_pipeline.run_kafka_producer scheduled__2025-04-22T00:00:00+00:00 [queued]>
[2025-04-23T05:21:20.883+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_delta_pipeline.run_kafka_producer scheduled__2025-04-22T00:00:00+00:00 [queued]>
[2025-04-23T05:21:20.883+0100] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-23T05:21:20.886+0100] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_kafka_producer> on 2025-04-22 00:00:00+00:00
[2025-04-23T05:21:20.889+0100] {standard_task_runner.py:72} INFO - Started process 77601 to run task
[2025-04-23T05:21:20.891+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'kafka_spark_delta_pipeline', 'run_kafka_producer', 'scheduled__2025-04-22T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/data_pipelines.py', '--cfg-path', '/var/folders/3w/7_wgs56n3c30fpsrg0g2mg_00000gn/T/tmp1xtb9swp']
[2025-04-23T05:21:20.892+0100] {standard_task_runner.py:105} INFO - Job 8: Subtask run_kafka_producer
[2025-04-23T05:21:20.906+0100] {task_command.py:467} INFO - Running <TaskInstance: kafka_spark_delta_pipeline.run_kafka_producer scheduled__2025-04-22T00:00:00+00:00 [running]> on host mac.home
[2025-04-23T05:21:20.968+0100] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='kafka_spark_delta_pipeline' AIRFLOW_CTX_TASK_ID='run_kafka_producer' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-22T00:00:00+00:00'
[2025-04-23T05:21:20.968+0100] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-23T05:21:20.968+0100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-23T05:21:20.968+0100] {logging_mixin.py:190} INFO - Current task name:run_kafka_producer state:running start_date:2025-04-23 04:21:20.882191+00:00
[2025-04-23T05:21:20.968+0100] {logging_mixin.py:190} INFO - Dag name:kafka_spark_delta_pipeline and current dag run status:running
[2025-04-23T05:21:20.969+0100] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T05:21:20.969+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T05:21:20.983+0100] {conn.py:614} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <checking_api_versions_recv> [IPv4 ('127.0.0.1', 9092)]>: Broker version identified as 2.6
[2025-04-23T05:21:20.983+0100] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv4 ('127.0.0.1', 9092)]>: Connection complete.
[2025-04-23T05:26:20.988+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T05:26:20.991+0100] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connected> [IPv4 ('127.0.0.1', 9092)]>: Connection complete.
[2025-04-23T05:26:20.991+0100] {conn.py:935} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=localhost:9092 <connected> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. 
[2025-04-23T06:04:54.169+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connected> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: Socket EVENT_READ without in-flight-requests
[2025-04-23T06:06:21.027+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T06:06:21.028+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T06:06:21.029+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T06:06:21.029+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T06:06:21.074+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T06:06:21.074+0100] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connected> [IPv4 ('127.0.0.1', 9092)]>: Connection complete.
[2025-04-23T06:31:13.569+0100] {job.py:229} INFO - Heartbeat recovered after 559.80 seconds
[2025-04-23T06:34:22.064+0100] {job.py:229} INFO - Heartbeat recovered after 183.48 seconds
[2025-04-23T06:49:34.876+0100] {job.py:229} INFO - Heartbeat recovered after 902.76 seconds
[2025-04-23T07:06:13.318+0100] {job.py:229} INFO - Heartbeat recovered after 903.16 seconds
[2025-04-23T07:21:56.421+0100] {job.py:229} INFO - Heartbeat recovered after 902.98 seconds
[2025-04-23T07:22:28.074+0100] {client_async.py:1147} INFO - Closing idle connection 1, last active 3666974 ms ago
[2025-04-23T07:22:28.075+0100] {conn.py:935} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connected> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. 
[2025-04-23T07:22:28.078+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T07:22:28.078+0100] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connected> [IPv4 ('127.0.0.1', 9092)]>: Connection complete.
[2025-04-23T07:37:39.580+0100] {job.py:229} INFO - Heartbeat recovered after 903.04 seconds
[2025-04-23T07:40:16.435+0100] {job.py:229} INFO - Heartbeat recovered after 111.70 seconds
[2025-04-23T07:58:11.668+0100] {job.py:229} INFO - Heartbeat recovered after 1075.23 seconds
[2025-04-23T08:16:01.361+0100] {job.py:229} INFO - Heartbeat recovered after 1064.68 seconds
[2025-04-23T08:22:56.078+0100] {job.py:229} INFO - Heartbeat recovered after 414.72 seconds
[2025-04-23T08:39:53.642+0100] {job.py:229} INFO - Heartbeat recovered after 1017.56 seconds
[2025-04-23T08:55:09.341+0100] {job.py:229} INFO - Heartbeat recovered after 915.70 seconds
[2025-04-23T09:10:26.984+0100] {job.py:229} INFO - Heartbeat recovered after 917.64 seconds
[2025-04-23T09:23:52.701+0100] {job.py:229} INFO - Heartbeat recovered after 805.72 seconds
[2025-04-23T09:40:48.490+0100] {job.py:229} INFO - Heartbeat recovered after 1010.77 seconds
[2025-04-23T09:57:45.233+0100] {job.py:229} INFO - Heartbeat recovered after 1016.74 seconds
[2025-04-23T10:14:04.881+0100] {job.py:229} INFO - Heartbeat recovered after 979.65 seconds
[2025-04-23T10:24:51.613+0100] {job.py:229} INFO - Heartbeat recovered after 646.73 seconds
[2025-04-23T10:36:01.639+0100] {job.py:229} INFO - Heartbeat recovered after 665.02 seconds
[2025-04-23T10:51:25.271+0100] {job.py:229} INFO - Heartbeat recovered after 903.55 seconds
[2025-04-23T11:00:30.512+0100] {job.py:229} INFO - Heartbeat recovered after 505.13 seconds
[2025-04-23T11:04:46.220+0100] {job.py:229} INFO - Heartbeat recovered after 250.69 seconds
[2025-04-23T11:06:06.920+0100] {client_async.py:1147} INFO - Closing idle connection 1, last active 13418836 ms ago
[2025-04-23T11:06:06.921+0100] {conn.py:935} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connected> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. 
[2025-04-23T11:06:06.927+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:06:06.928+0100] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connected> [IPv4 ('127.0.0.1', 9092)]>: Connection complete.
[2025-04-23T11:10:23.711+0100] {job.py:229} INFO - Heartbeat recovered after 227.12 seconds
[2025-04-23T11:26:10.632+0100] {job.py:229} INFO - Heartbeat recovered after 941.91 seconds
[2025-04-23T11:30:25.902+0100] {client_async.py:1147} INFO - Closing idle connection 1, last active 1458970 ms ago
[2025-04-23T11:30:25.904+0100] {conn.py:935} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connected> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. 
[2025-04-23T11:30:25.906+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:30:25.906+0100] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connected> [IPv4 ('127.0.0.1', 9092)]>: Connection complete.
[2025-04-23T11:45:41.656+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connected> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: Socket EVENT_READ without in-flight-requests
[2025-04-23T11:50:25.918+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:50:25.920+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:25.920+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:25.921+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:50:25.964+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:50:25.964+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:25.964+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:25.965+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:50:25.965+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:25.965+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:25.965+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:50:26.067+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:50:26.067+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:26.067+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:26.068+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:50:26.068+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:26.068+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:26.068+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:50:26.271+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:50:26.271+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:26.271+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:26.272+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:50:26.272+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:26.272+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:26.272+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:50:26.606+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:50:26.607+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:26.607+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:26.607+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:50:26.607+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:26.608+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:26.608+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:50:27.307+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:50:27.307+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:27.307+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:27.307+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:50:27.308+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:27.308+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:27.308+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:50:29.088+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:50:29.088+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:29.089+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:29.089+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:50:29.089+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:29.089+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:29.089+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:50:32.454+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:50:32.455+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:32.455+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:32.455+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:50:32.456+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:32.456+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:32.456+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:50:39.648+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:50:39.649+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:39.649+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:39.649+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:50:39.649+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:39.650+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:39.650+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:50:50.313+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:50:50.314+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:50.314+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:50.314+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:50:50.314+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:50:50.315+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:50:50.315+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:51:12.716+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:51:12.718+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:51:12.718+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:51:12.718+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:51:12.718+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:51:12.719+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:51:12.719+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:51:45.995+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:51:45.996+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:51:45.996+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:51:45.997+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:51:45.997+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:51:45.997+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:51:45.997+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:52:17.938+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:52:17.939+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:52:17.939+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:52:17.939+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:52:17.939+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:52:17.940+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:52:17.940+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:52:46.720+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:52:46.723+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:52:46.723+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:52:46.723+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:52:46.723+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:52:46.723+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:52:46.724+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:53:14.985+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:53:14.987+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:53:14.987+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:53:14.987+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:53:14.987+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:53:14.987+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:53:14.988+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:53:50.599+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:53:50.601+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:53:50.601+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:53:50.601+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:53:50.601+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:53:50.602+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:53:50.602+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:54:17.385+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:54:17.386+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:54:17.387+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:54:17.387+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:54:17.387+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:54:17.387+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:54:17.387+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:54:48.667+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:54:48.669+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:54:48.669+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:54:48.669+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:54:48.669+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:54:48.669+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:54:48.670+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:55:14.993+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:55:14.995+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:55:14.995+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:55:14.995+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:55:14.996+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:55:14.996+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:55:14.996+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:55:43.476+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:55:43.477+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:55:43.478+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:55:43.478+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:55:43.478+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:55:43.478+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:55:43.478+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:56:19.021+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:56:19.023+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:56:19.023+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:56:19.023+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:56:19.024+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:56:19.024+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:56:19.024+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:56:54.387+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:56:54.388+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:56:54.388+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:56:54.389+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:56:54.389+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:56:54.389+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:56:54.389+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:57:19.812+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:57:19.813+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:57:19.813+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:57:19.814+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:57:19.814+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:57:19.814+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:57:19.814+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:57:47.263+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:57:47.264+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:57:47.265+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:57:47.265+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:57:47.265+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:57:47.265+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:57:47.266+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:58:22.900+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:58:22.901+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:58:22.902+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:58:22.902+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:58:22.902+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:58:22.902+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:58:22.902+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:58:58.590+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:58:58.591+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:58:58.591+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:58:58.591+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:58:58.592+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:58:58.592+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:58:58.592+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T11:59:24.487+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T11:59:24.487+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:59:24.487+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:59:24.487+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T11:59:24.488+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T11:59:24.488+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T11:59:24.488+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T12:00:00.141+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T12:00:00.142+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T12:00:00.142+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T12:00:00.143+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T12:00:00.143+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T12:00:00.143+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T12:00:00.143+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T12:00:35.343+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T12:00:35.345+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T12:00:35.345+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T12:00:35.345+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: connecting to localhost:9092 [('::1', 9092, 0, 0) IPv6]
[2025-04-23T12:00:35.345+0100] {conn.py:428} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Connect attempt returned error 61. Disconnecting.
[2025-04-23T12:00:35.345+0100] {conn.py:935} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv6 ('::1', 9092, 0, 0)]>: Closing connection. KafkaConnectionError: 61 ECONNREFUSED
[2025-04-23T12:00:35.346+0100] {client_async.py:388} WARNING - Node 1 connection failed -- refreshing metadata
[2025-04-23T12:01:05.333+0100] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connecting> [IPv4 ('127.0.0.1', 9092)]>: connecting to localhost:9092 [('127.0.0.1', 9092) IPv4]
[2025-04-23T12:01:05.334+0100] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=localhost:9092 <connected> [IPv4 ('127.0.0.1', 9092)]>: Connection complete.
[2025-04-23T12:29:49.438+0100] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-04-23T12:29:49.439+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-23T12:29:49.442+0100] {process_utils.py:132} INFO - Sending 15 to group 77601. PIDs of all processes in the group: [77601]
[2025-04-23T12:29:49.443+0100] {process_utils.py:87} INFO - Sending the signal 15 to group 77601
[2025-04-23T12:30:49.476+0100] {process_utils.py:150} WARNING - process psutil.Process(pid=77601, name='Python', status='running', started='05:21:20') did not respond to SIGTERM. Trying SIGKILL
[2025-04-23T12:30:49.478+0100] {process_utils.py:87} INFO - Sending the signal 9 to group 77601
[2025-04-23T12:30:49.485+0100] {process_utils.py:80} INFO - Process psutil.Process(pid=77601, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='05:21:20') (77601) terminated with exit code -9
[2025-04-23T12:30:49.486+0100] {standard_task_runner.py:190} ERROR - ('Job 8 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
