[2025-04-23T02:28:56.900+0100] {processor.py:186} INFO - Started process (PID=57701) to work on /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:28:56.900+0100] {processor.py:914} INFO - Processing file /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-23T02:28:56.901+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:28:56.901+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:28:56.912+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:28:56.910+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-23T02:28:56.912+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:28:56.912+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-23T02:28:56.912+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:28:56.940+0100] {processor.py:208} INFO - Processing /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-04-23T02:30:21.543+0100] {processor.py:186} INFO - Started process (PID=57873) to work on /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:30:21.544+0100] {processor.py:914} INFO - Processing file /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-23T02:30:21.544+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:30:21.544+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:30:21.556+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:30:21.554+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-23T02:30:21.556+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:30:21.556+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-23T02:30:21.556+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:30:21.583+0100] {processor.py:208} INFO - Processing /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-04-23T02:32:10.537+0100] {processor.py:186} INFO - Started process (PID=58088) to work on /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:32:10.538+0100] {processor.py:914} INFO - Processing file /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-23T02:32:10.539+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:32:10.539+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:32:10.550+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:32:10.548+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-23T02:32:10.550+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:32:10.550+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-23T02:32:10.550+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:32:10.578+0100] {processor.py:208} INFO - Processing /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-04-23T02:34:46.880+0100] {processor.py:186} INFO - Started process (PID=58502) to work on /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:34:46.881+0100] {processor.py:914} INFO - Processing file /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-23T02:34:46.882+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:34:46.882+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:34:46.893+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:34:46.891+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-23T02:34:46.893+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:34:46.893+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-23T02:34:46.893+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:34:46.921+0100] {processor.py:208} INFO - Processing /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-04-23T02:36:10.232+0100] {processor.py:186} INFO - Started process (PID=58623) to work on /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:36:10.233+0100] {processor.py:914} INFO - Processing file /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-23T02:36:10.234+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:36:10.234+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:36:10.245+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:36:10.243+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-23T02:36:10.245+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:36:10.245+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-23T02:36:10.245+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:36:10.274+0100] {processor.py:208} INFO - Processing /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2025-04-23T02:37:59.441+0100] {processor.py:186} INFO - Started process (PID=58830) to work on /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:37:59.442+0100] {processor.py:914} INFO - Processing file /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-23T02:37:59.443+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:37:59.443+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:37:59.454+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:37:59.452+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-23T02:37:59.454+0100] {logging_mixin.py:190} INFO - [2025-04-23T02:37:59.454+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-23T02:37:59.454+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-23T02:37:59.482+0100] {processor.py:208} INFO - Processing /Users/francisayanbadejo/venvs_projects/my_proj/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
